2023-08-23 14:48:50.353753: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-23 14:49:14.621759: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-23 14:49:14.625171: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2023-08-23 14:53:20.398374: W tensorflow/core/framework/op_kernel.cc:1768] INVALID_ARGUMENT: ValueError: cannot reshape array of size 63488 into shape (36377,64)
Traceback (most recent call last):

  File "/esat/spchtemp/scratch/lbollens/program_installs/anaconda3/envs/tf2_11/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 271, in __call__
    ret = func(*args)

  File "/esat/spchtemp/scratch/lbollens/program_installs/anaconda3/envs/tf2_11/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/esat/spchtemp/scratch/lbollens/program_installs/anaconda3/envs/tf2_11/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1035, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/esat/spchtemp/scratch/lbollens/experiments/icassp2024Challenge/auditory-eeg-challenge-2024-code/util/dataset_generator.py", line 378, in __call__
    yield self.__getitem__(idx)

  File "/esat/spchtemp/scratch/lbollens/experiments/icassp2024Challenge/auditory-eeg-challenge-2024-code/util/dataset_generator.py", line 360, in __getitem__
    f = np.load(feature).astype(np.float32)

  File "/esat/spchtemp/scratch/lbollens/program_installs/anaconda3/envs/tf2_11/lib/python3.10/site-packages/numpy/lib/npyio.py", line 432, in load
    return format.read_array(fid, allow_pickle=allow_pickle,

  File "/esat/spchtemp/scratch/lbollens/program_installs/anaconda3/envs/tf2_11/lib/python3.10/site-packages/numpy/lib/format.py", line 820, in read_array
    array.shape = shape

ValueError: cannot reshape array of size 63488 into shape (36377,64)


Traceback (most recent call last):
  File "/esat/spchtemp/scratch/lbollens/experiments/icassp2024Challenge/auditory-eeg-challenge-2024-code/task2_regression/experiments/linear_baseline_mel.py", line 122, in <module>
    model.fit(
  File "/esat/spchtemp/scratch/lbollens/program_installs/anaconda3/envs/tf2_11/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/esat/spchtemp/scratch/lbollens/program_installs/anaconda3/envs/tf2_11/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

ValueError: cannot reshape array of size 63488 into shape (36377,64)
Traceback (most recent call last):

  File "/esat/spchtemp/scratch/lbollens/program_installs/anaconda3/envs/tf2_11/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 271, in __call__
    ret = func(*args)

  File "/esat/spchtemp/scratch/lbollens/program_installs/anaconda3/envs/tf2_11/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/esat/spchtemp/scratch/lbollens/program_installs/anaconda3/envs/tf2_11/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1035, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/esat/spchtemp/scratch/lbollens/experiments/icassp2024Challenge/auditory-eeg-challenge-2024-code/util/dataset_generator.py", line 378, in __call__
    yield self.__getitem__(idx)

  File "/esat/spchtemp/scratch/lbollens/experiments/icassp2024Challenge/auditory-eeg-challenge-2024-code/util/dataset_generator.py", line 360, in __getitem__
    f = np.load(feature).astype(np.float32)

  File "/esat/spchtemp/scratch/lbollens/program_installs/anaconda3/envs/tf2_11/lib/python3.10/site-packages/numpy/lib/npyio.py", line 432, in load
    return format.read_array(fid, allow_pickle=allow_pickle,

  File "/esat/spchtemp/scratch/lbollens/program_installs/anaconda3/envs/tf2_11/lib/python3.10/site-packages/numpy/lib/format.py", line 820, in read_array
    array.shape = shape

ValueError: cannot reshape array of size 63488 into shape (36377,64)


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_1026]
